### ISSUE TITLE
checking `clickedOnList` after the fetch finishes

### ISSUE THREAD

**Issue by Karyum** [WebAhead11/node-auto#8]
https://github.com/WebAhead11/node-auto/blob/main/public/main.js#L30

so if `clickedOnList` is false then you don't show the autocomplete. you could just say if `clickedOnList` is true then run the fetch.

cause you don't even need the fetch when `clickedOnList` is false

**Comment by kassimbashir** [comment]
I'm not sure you understand what I meant with this variable. 
This is meant to solve the issue of having to click twice on an item from the data list in order for the datalist to disappear.
the idea is, if the user is typing, then show the option. else, if he chose an item from the list using the mouse then don't show.
